/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    admins: AdminAuthOperations;
  };
  blocks: {};
  collections: {
    admins: Admin;
    media: Media;
    products: Product;
    variants: Variant;
    orders: Order;
    'order-items': OrderItem;
    tickets: Ticket;
    addresses: Address;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    products: {
      variants: 'variants';
    };
    orders: {
      items: 'order-items';
    };
  };
  collectionsSelect: {
    admins: AdminsSelect<false> | AdminsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    variants: VariantsSelect<false> | VariantsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'order-items': OrderItemsSelect<false> | OrderItemsSelect<true>;
    tickets: TicketsSelect<false> | TicketsSelect<true>;
    addresses: AddressesSelect<false> | AddressesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Admin;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: number;
  name: string;
  role: 'superadmin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'admins';
}
/**
 * Imágenes de producto, fichas técnicas PDF y otros documentos.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Requerido para imágenes de producto. Describe la imagen para lectores de pantalla y SEO. No aplica para PDFs.
   */
  alt?: string | null;
  /**
   * Opcional. Aparece debajo de la imagen en el detalle del producto.
   */
  caption?: string | null;
  /**
   * Usado por el filtro de relaciones en Productos para mostrar solo el tipo correcto en cada campo (imágenes → image, ficha técnica → datasheet, meta → og-image).
   */
  documentType: 'image' | 'datasheet' | 'og-image' | 'document';
  /**
   * Marcado como eliminado. El archivo se oculta del storefront pero se conserva en la base de datos.
   */
  isDeleted?: boolean | null;
  /**
   * Fecha y hora en que se marcó como eliminado.
   */
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Catálogo multi-categoría: interruptores, gabinetes, unicanal, fijación, soportería y herramientas.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * Nombre completo que aparece en el catálogo y en el detalle.
   */
  name: string;
  /**
   * Generado automáticamente desde el nombre. Solo minúsculas, números y guiones. Cambiar después de publicar puede romper enlaces existentes.
   */
  slug: string;
  /**
   * Ej. Siemens, ABB, Schneider Electric.
   */
  brand: string;
  /**
   * Código exacto del fabricante. Ej. 5SL6110-7.
   */
  model: string;
  /**
   * Define qué campos técnicos se muestran abajo. Los specs específicos por SKU (precio, stock, medida exacta) van en cada Variante.
   */
  category: 'interruptores' | 'gabinetes_tableros' | 'unicanal' | 'fijacion' | 'soporteria' | 'herramientas_accesorios';
  /**
   * Línea o serie del fabricante. Ej. I-LINE, Caja Moldeada, Power Pact, ED63B, FXD63B, NF, NQ. Opcional.
   */
  productLine?: string | null;
  /**
   * Máx. 120 caracteres. Aparece en tarjetas del catálogo.
   */
  shortDescription?: string | null;
  /**
   * Descripción detallada para la página de detalle del producto.
   */
  description: string;
  /**
   * Características técnicas adicionales: capacidad de ruptura, normas, temperatura de operación, etc.
   */
  technicalSummary?: string | null;
  /**
   * Palabras clave para búsqueda interna. Ej. industrial, residencial, riel DIN.
   */
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Suma de todas las variantes. Actualizar manualmente o via webhook de inventario.
   */
  stock?: number | null;
  /**
   * Corriente nominal en Amperes. Ej. 10, 16, 25, 63.
   */
  amperage?: number | null;
  poles?: ('1' | '2' | '3' | '4') | null;
  /**
   * Tensión nominal de operación. Ej. 120, 240, 380, 480.
   */
  voltage?: number | null;
  tripCurve?: ('B' | 'C' | 'D') | null;
  /**
   * Capacidad de ruptura en kA. Ej. 10, 25, 65.
   */
  interruptingCapacity?: number | null;
  mountingType?: ('iline' | 'screw') | null;
  /**
   * Ej. Caja moldeada, Power Pact, Master Pact.
   */
  breakerType?: string | null;
  /**
   * Designación de frame del fabricante. Ej. FA, KA, LA, MA.
   */
  frame?: string | null;
  boardType?: ('nf' | 'nq' | 'iline' | 'autosoportado' | 'gabinete') | null;
  nemaRating?: ('1' | '3r') | null;
  /**
   * Capacidad de corriente del tablero/gabinete. Ej. 100, 400, 1200, 5000.
   */
  amperageCapacity?: number | null;
  enclosureUse?: ('interior' | 'intemperie') | null;
  spaces?: number | null;
  circuits?: number | null;
  /**
   * Ej. I-LINE, Caja Moldeada.
   */
  compatibleBreakerLine?: string | null;
  channelType?: ('solido' | 'perforado') | null;
  gauge?: ('14' | '16' | '18') | null;
  /**
   * Ej. 4 × 2", 4 × 4".
   */
  dimensions?: string | null;
  /**
   * Ej. 3.05 m (largo estándar).
   */
  length?: string | null;
  /**
   * Ej. Galvanizado.
   */
  finish?: string | null;
  customLengthAvailable?: boolean | null;
  /**
   * Ej. Expanzor Z, Expanzor TX, ADI, Ancla-Arpón, Cuña.
   */
  anchorType?: string | null;
  /**
   * Cantidad de piezas en presentación de caja/mayoreo.
   */
  boxQuantity?: number | null;
  /**
   * Ej. Varilla roscada, Tuerca resorte, Mordaza, Trapecio, Cinta perforada.
   */
  supportType?: string | null;
  compatibleWithUnicanal?: boolean | null;
  /**
   * Ej. Clavos, Cartuchos, Pernos, Brocas SDS.
   */
  accessoryType?: string | null;
  /**
   * Ej. Pistola de fijación, Rotomartillo.
   */
  compatibleTool?: string | null;
  /**
   * Ej. Concreto, Fierro estructural, Alta velocidad.
   */
  application?: string | null;
  /**
   * Ej. Por pieza, Caja, Ciento, Rollo.
   */
  presentation?: string | null;
  /**
   * Ej. Acero, Latón, Acero galvanizado.
   */
  material?: string | null;
  /**
   * Medida nominal. Ej. 3/16", 1/4", 3/4".
   */
  dimDiameter?: string | null;
  /**
   * Ej. 1 m, 3 m, 2.1/2".
   */
  dimLength?: string | null;
  /**
   * Las variantes se gestionan desde la colección Variantes.
   */
  variants?: {
    docs?: (number | Variant)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Activa esta opción para crear automáticamente la primera variante de venta al guardar el producto. Se desactiva solo después de crearla. Si ya existe una variante con el mismo SKU, se omite.
   */
  createInitialVariant?: boolean | null;
  /**
   * Código único. Ej. SIEM-5SL6110-7-PIE. Requerido si activas la creación.
   */
  initialVariantSku?: string | null;
  initialVariantSaleType?: ('piece' | 'box' | 'lot') | null;
  /**
   * Para pieza: 1. Para caja o lote: cantidad incluida en el precio.
   */
  initialVariantUnitsPerPackage?: number | null;
  /**
   * Precio de venta al público. Ej. 299.00
   */
  initialVariantPrice?: number | null;
  initialVariantStock?: number | null;
  /**
   * Subir en Media (documentType: Imagen de producto) antes de seleccionar aquí.
   */
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Subir en Media (documentType: Ficha técnica / Datasheet) antes de seleccionar.
   */
  datasheet?: (number | null) | Media;
  /**
   * Si se deja vacío, se usa el nombre del producto. Máx. 60 caracteres recomendado.
   */
  metaTitle?: string | null;
  /**
   * Si se deja vacía, se usa la descripción completa truncada. Máx. 160 caracteres recomendado.
   */
  metaDescription?: string | null;
  /**
   * Imagen que aparece al compartir en redes sociales. Recomendado: 1200×630 px.
   */
  metaImage?: (number | null) | Media;
  /**
   * Desactivar para ocultar el producto del storefront sin eliminarlo. Los admins siempre pueden verlo.
   */
  isActive?: boolean | null;
  /**
   * Aparece en la sección 'Productos destacados' de la página de inicio.
   */
  featured?: boolean | null;
  /**
   * Marcado como eliminado. El producto y sus variantes se ocultan del storefront pero se conservan para el historial de órdenes.
   */
  isDeleted?: boolean | null;
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Presentaciones de venta (pieza, caja, lote) de cada producto.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants".
 */
export interface Variant {
  id: number;
  /**
   * Producto al que pertenece esta variante.
   */
  product: number | Product;
  /**
   * Código único de referencia. Debe ser único en todo el catálogo. Ej. SIEM-5SL6110-7-PIE, SIEM-5SL6110-7-CAJ12. Cambiar el SKU después de crear órdenes puede romper los snapshots históricos.
   */
  sku: string;
  /**
   * Determina cómo se presenta al cliente en el storefront.
   */
  saleType: 'piece' | 'box' | 'lot';
  /**
   * Para pieza: 1. Para caja o lote: número de unidades incluidas en el precio.
   */
  unitsPerPackage: number;
  /**
   * Precio de venta al público. Debe incluir IVA. No ingresar centavos: ej. 299.00
   */
  price: number;
  /**
   * Unidades disponibles de esta presentación específica.
   */
  stock: number;
  /**
   * Valor exacto de este SKU que la diferencia de otras variantes. Ej. "63 A", "Calibre 14 · 4×2\" · 3.05 m", "3/4\" × 12\"".
   */
  variantSpec?: string | null;
  /**
   * Forma de venta. Ej. "Pieza", "Caja de 100", "Rollo 25 m".
   */
  presentation?: string | null;
  /**
   * Unidad mostrada al cliente. Ej. "pza", "caja", "rollo", "m".
   */
  unitLabel?: string | null;
  /**
   * Desactivar para ocultar esta presentación sin eliminarla. Las variantes inactivas no aparecen en el storefront.
   */
  isActive?: boolean | null;
  /**
   * Marcada como eliminada cuando el producto padre se elimina. Se conserva para el historial de órdenes.
   */
  isDeleted?: boolean | null;
  /**
   * Fecha y hora en que se marcó como eliminada.
   */
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Órdenes de compra de clientes del storefront.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  /**
   * Se genera automáticamente al crear la orden (ej. ORD-000042). Es el identificador que el cliente envía por WhatsApp y el que puedes buscar en este listado.
   */
  orderNumber?: string | null;
  /**
   * Evita órdenes duplicadas si el checkout se reenvía. Se genera en el cliente. No editar manualmente.
   */
  idempotencyKey?: string | null;
  customer: {
    customerName?: string | null;
    customerEmail: string;
    /**
     * ID del usuario en la tabla `users` de Auth.js. No editar manualmente.
     */
    customerAuthId?: string | null;
  };
  /**
   * Flujo manual: el cliente inicia la orden por WhatsApp. Solicita el pago, recibe el comprobante y marca «Pago confirmado» (esto descuenta el stock). Marca «Entregada» al completar el envío.
   */
  status: 'pending' | 'payment_pending' | 'paid' | 'fulfilled' | 'cancelled';
  /**
   * Indica si el inventario ya se descontó por esta orden. Se administra automáticamente: se descuenta al confirmar el pago y se restaura si la orden se cancela. No editar manualmente.
   */
  stockDecremented?: boolean | null;
  /**
   * Fecha en que el cliente abrió el mensaje de WhatsApp desde su orden. Sirve para saber si ya inició contacto. Se registra automáticamente.
   */
  whatsappSentAt?: string | null;
  shipping?: {
    name?: string | null;
    address?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    phone?: string | null;
  };
  pricing: {
    /**
     * Suma de artículos antes de envío.
     */
    subtotal: number;
    shipping: number;
    /**
     * Subtotal + envío. IVA incluido.
     */
    total: number;
    taxIncluded?: boolean | null;
  };
  /**
   * Comprobantes de transferencia o pago (imagen o PDF). Los sube el cliente desde el detalle de su orden, o el administrador si los recibió por otro medio (WhatsApp, correo, etc.). Revísalos antes de confirmar el pago.
   */
  paymentProofs?:
    | {
        file: number | Media;
        uploadedBy?: ('customer' | 'admin') | null;
        uploadedAt?: string | null;
        /**
         * Revisa cada comprobante. «Aceptado» no confirma el pago por sí solo (usa el estado de la orden para eso); «Rechazado» notifica al cliente.
         */
        reviewStatus?: ('pending' | 'accepted' | 'rejected') | null;
        /**
         * Motivo visible para el cliente (ej. «el monto no coincide»). Se incluye en el correo al rechazar.
         */
        reviewNote?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Registro automático de cada cambio de estado (quién, cuándo y por qué). Solo lectura.
   */
  statusHistory?:
    | {
        status?: ('pending' | 'payment_pending' | 'paid' | 'fulfilled' | 'cancelled') | null;
        changedAt?: string | null;
        /**
         * "customer", "admin" o "system".
         */
        changedBy?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Instrucciones de entrega proporcionadas por el cliente al hacer el pedido.
   */
  notes?: string | null;
  /**
   * Notas privadas del equipo sobre esta orden. Nunca visibles para el cliente.
   */
  internalNotes?: string | null;
  items?: {
    docs?: (number | OrderItem)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Líneas de cada orden. Los campos snapshot son inmutables: preservan el estado del catálogo al momento de la compra, aunque después cambie nombre o precio.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-items".
 */
export interface OrderItem {
  id: number;
  order: number | Order;
  /**
   * Referencia al producto actual. Puede cambiar si el producto es editado; use los campos snapshot para el dato histórico.
   */
  product: number | Product;
  variant: number | Variant;
  /**
   * Copia del nombre al momento de la compra. No editar.
   */
  productNameSnapshot: string;
  /**
   * Copia del SKU al momento de la compra. No editar.
   */
  variantSkuSnapshot: string;
  /**
   * Copia de la etiqueta de la variante (ej. «Caja × 10 piezas») al momento de la compra. No editar.
   */
  variantLabelSnapshot?: string | null;
  /**
   * Número de unidades compradas de esta variante.
   */
  quantity: number;
  /**
   * Precio unitario snapshot. IVA incluido. No editar.
   */
  unitPrice: number;
  /**
   * quantity × unitPrice. No editar.
   */
  total: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Tickets de soporte creados por clientes del storefront.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tickets".
 */
export interface Ticket {
  id: number;
  clientInfo: {
    customerEmail: string;
    /**
     * ID en la tabla `users` de Auth.js. Se vincula en Fase 6. No editar.
     */
    customerAuthId?: string | null;
  };
  inquiry: {
    /**
     * Resumen breve del problema o consulta.
     */
    subject: string;
    /**
     * Descripción detallada enviada por el cliente.
     */
    message: string;
  };
  /**
   * Vincular opcionalmente con un producto u orden relacionados.
   */
  relations?: {
    product?: (number | null) | Product;
    order?: (number | null) | Order;
  };
  /**
   * Alta para devoluciones, defectos o bloqueos de operación.
   */
  priority: 'high' | 'medium' | 'low';
  status: 'open' | 'in_progress' | 'resolved';
  /**
   * Nunca visibles para el cliente. Historial de acciones, notas de escalada, etc.
   */
  adminNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Domicilios guardados por los clientes para el checkout.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses".
 */
export interface Address {
  id: number;
  /**
   * session.user.id del cliente (JWT sub).
   */
  customerAuthId: string;
  customerEmail: string;
  /**
   * Nombre del domicilio. Ej: "Casa", "Oficina".
   */
  label: string;
  fullName: string;
  phone?: string | null;
  /**
   * Calle, número exterior e interior, colonia.
   */
  addressLine1: string;
  /**
   * Opcional: referencias adicionales.
   */
  addressLine2?: string | null;
  city: string;
  state: string;
  postalCode: string;
  country: string;
  /**
   * Si está marcado, se selecciona automáticamente en el checkout.
   */
  isDefault?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'admins';
        value: number | Admin;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'variants';
        value: number | Variant;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'order-items';
        value: number | OrderItem;
      } | null)
    | ({
        relationTo: 'tickets';
        value: number | Ticket;
      } | null)
    | ({
        relationTo: 'addresses';
        value: number | Address;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'admins';
    value: number | Admin;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'admins';
    value: number | Admin;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins_select".
 */
export interface AdminsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  documentType?: T;
  isDeleted?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  brand?: T;
  model?: T;
  category?: T;
  productLine?: T;
  shortDescription?: T;
  description?: T;
  technicalSummary?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  stock?: T;
  amperage?: T;
  poles?: T;
  voltage?: T;
  tripCurve?: T;
  interruptingCapacity?: T;
  mountingType?: T;
  breakerType?: T;
  frame?: T;
  boardType?: T;
  nemaRating?: T;
  amperageCapacity?: T;
  enclosureUse?: T;
  spaces?: T;
  circuits?: T;
  compatibleBreakerLine?: T;
  channelType?: T;
  gauge?: T;
  dimensions?: T;
  length?: T;
  finish?: T;
  customLengthAvailable?: T;
  anchorType?: T;
  boxQuantity?: T;
  supportType?: T;
  compatibleWithUnicanal?: T;
  accessoryType?: T;
  compatibleTool?: T;
  application?: T;
  presentation?: T;
  material?: T;
  dimDiameter?: T;
  dimLength?: T;
  variants?: T;
  createInitialVariant?: T;
  initialVariantSku?: T;
  initialVariantSaleType?: T;
  initialVariantUnitsPerPackage?: T;
  initialVariantPrice?: T;
  initialVariantStock?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  datasheet?: T;
  metaTitle?: T;
  metaDescription?: T;
  metaImage?: T;
  isActive?: T;
  featured?: T;
  isDeleted?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants_select".
 */
export interface VariantsSelect<T extends boolean = true> {
  product?: T;
  sku?: T;
  saleType?: T;
  unitsPerPackage?: T;
  price?: T;
  stock?: T;
  variantSpec?: T;
  presentation?: T;
  unitLabel?: T;
  isActive?: T;
  isDeleted?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  idempotencyKey?: T;
  customer?:
    | T
    | {
        customerName?: T;
        customerEmail?: T;
        customerAuthId?: T;
      };
  status?: T;
  stockDecremented?: T;
  whatsappSentAt?: T;
  shipping?:
    | T
    | {
        name?: T;
        address?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        phone?: T;
      };
  pricing?:
    | T
    | {
        subtotal?: T;
        shipping?: T;
        total?: T;
        taxIncluded?: T;
      };
  paymentProofs?:
    | T
    | {
        file?: T;
        uploadedBy?: T;
        uploadedAt?: T;
        reviewStatus?: T;
        reviewNote?: T;
        id?: T;
      };
  statusHistory?:
    | T
    | {
        status?: T;
        changedAt?: T;
        changedBy?: T;
        note?: T;
        id?: T;
      };
  notes?: T;
  internalNotes?: T;
  items?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-items_select".
 */
export interface OrderItemsSelect<T extends boolean = true> {
  order?: T;
  product?: T;
  variant?: T;
  productNameSnapshot?: T;
  variantSkuSnapshot?: T;
  variantLabelSnapshot?: T;
  quantity?: T;
  unitPrice?: T;
  total?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tickets_select".
 */
export interface TicketsSelect<T extends boolean = true> {
  clientInfo?:
    | T
    | {
        customerEmail?: T;
        customerAuthId?: T;
      };
  inquiry?:
    | T
    | {
        subject?: T;
        message?: T;
      };
  relations?:
    | T
    | {
        product?: T;
        order?: T;
      };
  priority?: T;
  status?: T;
  adminNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses_select".
 */
export interface AddressesSelect<T extends boolean = true> {
  customerAuthId?: T;
  customerEmail?: T;
  label?: T;
  fullName?: T;
  phone?: T;
  addressLine1?: T;
  addressLine2?: T;
  city?: T;
  state?: T;
  postalCode?: T;
  country?: T;
  isDefault?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Configuración global del storefront. Cambios aquí afectan toda la tienda.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  store: {
    storeName: string;
    /**
     * Dirección visible para clientes. Debe ser un email válido.
     */
    supportEmail?: string | null;
    /**
     * Opcional. Ej. +52 55 1234 5678. Se muestra en el footer y soporte.
     */
    storePhone?: string | null;
    /**
     * Opcional. Número con código de país, sin espacios ni guiones. Ej. 5215512345678. Se usa para generar el enlace wa.me/{número}.
     */
    whatsapp?: string | null;
    /**
     * Opcional. Ej. Lun–Vie 9:00–18:00, Sáb 10:00–14:00 (hora Ciudad de México).
     */
    businessHours?: string | null;
  };
  pricing: {
    /**
     * Costo de envío fijo para todas las órdenes. 0 = envío gratis.
     */
    flatShippingRate: number;
    currency: 'MXN' | 'USD';
    /**
     * Si está activo, se muestra 'IVA incluido' en el storefront. No afecta los precios almacenados en Variantes.
     */
    taxIncludedByDefault?: boolean | null;
  };
  /**
   * Datos bancarios e instrucciones de pago. Se muestran al cliente en su orden, en el mensaje de WhatsApp y en el correo de confirmación.
   */
  payment?: {
    /**
     * Ej. BBVA, Santander.
     */
    bankName?: string | null;
    accountHolder?: string | null;
    /**
     * 18 dígitos. Es el dato principal para transferencias.
     */
    clabe?: string | null;
    /**
     * Opcional.
     */
    accountNumber?: string | null;
    /**
     * Texto libre. Ej. «Envía tu comprobante por WhatsApp o desde tu orden».
     */
    paymentInstructions?: string | null;
    /**
     * Opcional. Las órdenes pendientes sin pago se cancelan automáticamente después de estos días (deja vacío para usar el valor por defecto, 7).
     */
    pendingOrderTtlDays?: number | null;
  };
  /**
   * Banner informativo opcional que aparece en la parte superior del storefront.
   */
  announcement?: {
    announcementEnabled?: boolean | null;
    /**
     * Se muestra solo cuando 'Mostrar banner' está activo. Ej. Envío gratis en pedidos mayores a $5,000 MXN.
     */
    announcementBanner?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  store?:
    | T
    | {
        storeName?: T;
        supportEmail?: T;
        storePhone?: T;
        whatsapp?: T;
        businessHours?: T;
      };
  pricing?:
    | T
    | {
        flatShippingRate?: T;
        currency?: T;
        taxIncludedByDefault?: T;
      };
  payment?:
    | T
    | {
        bankName?: T;
        accountHolder?: T;
        clabe?: T;
        accountNumber?: T;
        paymentInstructions?: T;
        pendingOrderTtlDays?: T;
      };
  announcement?:
    | T
    | {
        announcementEnabled?: T;
        announcementBanner?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}