import { NotFoundPage } from "@payloadcms/next/views";
// importMap.js is generated by `bun run payload:importmap` into the admin/ dir
import { importMap } from "../importMap.js";
import configPromise from "@payload-config";

type Args = {
  params: Promise<{ segments: string[] }>;
  searchParams: Promise<{ [key: string]: string | string[] }>;
};

const NotFound = ({ params, searchParams }: Args) => {
  return NotFoundPage({ config: configPromise, importMap, params, searchParams });
};

export default NotFound;
