import { RootPage, generatePageMetadata } from "@payloadcms/next/views";
// importMap.js is generated by `bun run payload:importmap` into the admin/ dir
import { importMap } from "../importMap.js";
import configPromise from "@payload-config";

type Args = {
  params: Promise<{ segments: string[] }>;
  searchParams: Promise<{ [key: string]: string | string[] }>;
};

export const generateMetadata = ({ params, searchParams }: Args) => {
  return generatePageMetadata({ config: configPromise, params, searchParams });
};

const Page = ({ params, searchParams }: Args) => {
  return RootPage({ config: configPromise, importMap, params, searchParams });
};

export default Page;
